import sourceLinksJson from "./source-links.json" with { type: "json" };

const REPO_BASE = "https://github.com/dcl-regenesislabs/wearable-validator/blob/main/packages/wearable-validator";

/** GitHub link to each check's implementation — generated by `npm run gen:sources`, drift is test-enforced. */
export const sourceLinks: Record<string, string> = Object.fromEntries(
  Object.entries(sourceLinksJson as Record<string, { file: string; line: number }>).map(([check, loc]) => [
    check,
    `${REPO_BASE}/${loc.file}#L${loc.line}`
  ])
);
